# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9239208c7b0d291cbbfb4591ea972ba8ca03b4de566194359dacb4e2ce10392e8267eb1c02095bfa7d44fb3b2dee28d220eb30471fc0d0b4d7a574d8e4dfaa5

test:
  secret_key_base: 2170c6bb88b6a7a5c992c235d12886a0c131e827ccb06743a4a58779631d51028b18e93a4b4709a8df2b64190b01dcc703e244a6b774741bd084e4ceedf3721a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
